[project]
name = "finetune-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets==3.5.0",
    "evaluate==0.4.3",
    "huggingface-hub==0.30.2",
    "numpy==2.2.4",
    "pandas==2.2.3",
    "peft==0.15.2",
    "pydash==8.0.5",
    "torch==2.6.0",
    "tqdm==4.67.1",
    "transformers==4.51.3",
    "trl==0.16.1",
    "wandb==0.19.9",
]
